export const couponsAndPrizes = [
  {
    title: {
      en: "Exclusive $50 Off",
      pt: "Desconto exclusivo de $50",
      ar: "خصم حصري 50 دولارًا",
      fa: "تخفیف ویژه ۵۰ دلاری",
    },
    description: {
      en: "Get $50 off on your next purchase",
      pt: "Ganhe $50 de desconto na sua próxima compra",
      ar: "احصل على خصم 50 دولارًا على مشترياتك القادمة",
      fa: "۵۰ دلار تخفیف روی خرید بعدی شما",
    },
    type: "coupon",
    amount: "50$",
    percentage: null,
    code: "TTL239",
    expiry: "2025-11-28",
    usageNumber: 3,
    used: false,
  },
  {
    title: {
      en: "Smartwatch Giveaway",
      pt: "Sorteio de Smartwatch",
      ar: "هاتف ذكي بالهدية",
      fa: "قرعه‌کشی ساعت هوشمند",
    },
    description: {
      en: "Win a brand new smartwatch",
      pt: "Ganhe um smartwatch novinho em folha",
      ar: "اربح ساعة ذكية جديدة كليًا",
      fa: "یک ساعت هوشمند نو برنده شوید",
    },
    type: "prize",
    amount: null,
    percentage: null,
    code: null,
    expiry: "2025-09-30",
    usageNumber: null,
    used: false,
  },
  {
    title: {
      en: "15% Off All Items",
      pt: "15% de desconto em todos os itens",
      ar: "خصم 15٪ على جميع العناصر",
      fa: "۱۵٪ تخفیف روی تمام محصولات",
    },
    description: {
      en: "Enjoy 15% off across the store",
      pt: "Aproveite 15% de desconto em toda a loja",
      ar: "استمتع بخصم 15٪ في جميع أنحاء المتجر",
      fa: "از ۱۵٪ تخفیف در کل فروشگاه لذت ببرید",
    },
    type: "prize",
    amount: null,
    percentage: "15%",
    code: null,
    expiry: "2025-09-30",
    usageNumber: 1,
    used: false,
  },
  {
    title: {
      en: "VIP $100 Discount",
      pt: "Desconto VIP de $100",
      ar: "خصم VIP بقيمة 100 دولار",
      fa: "تخفیف ۱۰۰ دلاری VIP",
    },
    description: {
      en: "Exclusive $100 discount for VIP customers",
      pt: "Desconto exclusivo de $100 para clientes VIP",
      ar: "خصم حصري بقيمة 100 دولار للعملاء المميزين",
      fa: "تخفیف انحصاری ۱۰۰ دلاری برای مشتریان VIP",
    },
    type: "coupon",
    amount: "100$",
    percentage: null,
    code: "VIP100",
    expiry: "2025-12-01",
    usageNumber: 10,
    used: false,
  },
  {
    title: {
      en: "20% Off Summer Collection",
      pt: "20% de desconto na coleção de verão",
      ar: "خصم 20٪ على مجموعة الصيف",
      fa: "۲۰٪ تخفیف روی مجموعه تابستان",
    },
    description: {
      en: "Save 20% on all summer collection items",
      pt: "Economize 20% em todos os itens da coleção de verão",
      ar: "وفر 20٪ على جميع عناصر مجموعة الصيف",
      fa: "۲۰٪ تخفیف روی همه محصولات تابستانی",
    },
    type: "coupon",
    amount: null,
    percentage: "20%",
    code: "SUM20",
    expiry: "2025-08-31",
    usageNumber: 200,
    used: false,
  },
  {
    title: {
      en: "Free Shipping Coupon",
      pt: "Cupom de Frete Grátis",
      ar: "قسيمة شحن مجاني",
      fa: "کد ارسال رایگان",
    },
    description: {
      en: "Get free shipping on your next order",
      pt: "Obtenha frete grátis no seu próximo pedido",
      ar: "احصل على شحن مجاني على طلبك القادم",
      fa: "ارسال رایگان برای سفارش بعدی شما",
    },
    type: "coupon",
    amount: null,
    percentage: null,
    code: "SHIPFREE",
    expiry: "2025-10-15",
    usageNumber: 500,
    used: false,
  },
  {
    title: {
      en: "Free T-shirt",
      pt: "Camiseta Grátis",
      ar: "تيشيرت مجاني",
      fa: "تی‌شرت رایگان",
    },
    description: {
      en: "Win a free branded T-shirt",
      pt: "Ganhe uma camiseta de marca grátis",
      ar: "اربح تيشيرت مجاني بعلامة تجارية",
      fa: "یک تی‌شرت رایگان با برند مخصوص دریافت کنید",
    },
    type: "prize",
    amount: null,
    percentage: null,
    code: null,
    expiry: "2025-11-20",
    usageNumber: null,
    used: false,
  },
  {
    title: {
      en: "Buy 1 Get 1 Free",
      pt: "Compre 1, Leve 1 Grátis",
      ar: "اشترِ 1 واحصل على 1 مجانًا",
      fa: "یک بخر، یکی رایگان ببر",
    },
    description: {
      en: "Buy one item and get another free",
      pt: "Compre um item e leve outro grátis",
      ar: "اشترِ سلعة واحصل على أخرى مجانًا",
      fa: "یک کالا بخر و یکی رایگان دریافت کن",
    },
    type: "coupon",
    amount: null,
    percentage: null,
    code: "B1G1",
    expiry: "2025-11-20",
    usageNumber: 150,
    used: false,
  },
  {
    title: {
      en: "Exclusive Backpack",
      pt: "Mochila Exclusiva",
      ar: "حقيبة ظهر حصرية",
      fa: "کوله‌پشتی اختصاصی",
    },
    description: {
      en: "Win an exclusive branded backpack",
      pt: "Ganhe uma mochila exclusiva da marca",
      ar: "اربح حقيبة ظهر حصرية ذات علامة تجارية",
      fa: "برنده یک کوله‌پشتی اختصاصی شوید",
    },
    type: "prize",
    amount: null,
    percentage: null,
    code: null,
    expiry: "2025-11-20",
    usageNumber: null,
    used: false,
  },
  {
    title: {
      en: "Free Coffee Mug",
      pt: "Caneca de Café Grátis",
      ar: "كوب قهوة مجاني",
      fa: "ماگ قهوه رایگان",
    },
    description: {
      en: "Receive a free coffee mug with your order",
      pt: "Receba uma caneca de café grátis com seu pedido",
      ar: "احصل على كوب قهوة مجاني مع طلبك",
      fa: "با سفارش خود یک ماگ قهوه رایگان دریافت کنید",
    },
    type: "prize",
    amount: null,
    percentage: null,
    code: null,
    expiry: "2025-11-20",
    usageNumber: null,
    used: false,
  },
  {
    title: {
      en: "$25 Gift Card",
      pt: "Cartão-presente de $25",
      ar: "بطاقة هدايا بقيمة 25 دولارًا",
      fa: "کارت هدیه ۲۵ دلاری",
    },
    description: {
      en: "Win a $25 gift card to spend on anything",
      pt: "Ganhe um cartão-presente de $25 para gastar em qualquer coisa",
      ar: "اربح بطاقة هدايا بقيمة 25 دولارًا لإنفاقها على أي شيء",
      fa: "برنده کارت هدیه ۲۵ دلاری شوید",
    },
    type: "prize",
    amount: null,
    percentage: null,
    code: null,
    expiry: "2025-11-20",
    usageNumber: null,
    used: false,
  },
  {
    title: {
      en: "Free Headphones",
      pt: "Fones de Ouvido Grátis",
      ar: "سماعات مجانية",
      fa: "هدفون رایگان",
    },
    description: {
      en: "Get a pair of free headphones with your win",
      pt: "Ganhe um par de fones de ouvido grátis",
      ar: "احصل على زوج من السماعات مجانًا",
      fa: "یک هدفون رایگان دریافت کنید",
    },
    type: "prize",
    amount: null,
    percentage: null,
    code: null,
    expiry: "2024-11-20",
    usageNumber: null,
    used: false,
  },
];
