import "@/app/globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import Footer from "@/components/layout/default/Footer";
import Header from "@/components/layout/default/Header";
import { NextIntlClientProvider } from "next-intl";
import { getLocaleDirection } from "@/lib/locale";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const param = await params
  const locale = await param.locale;
  const messages = (await import(`@/i18n/locales/${locale}.json`)).default;
  const dir = getLocaleDirection(locale)

  return (
    <html dir={dir} lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />

          <main className="min-h-screen">
          {children}
          </main>

          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
